with Ada.Strings.Unbounded; use Ada.Strings.Unbounded;

package Manufacturer_Codes is

   -- 11-bit key type
   type Hex_Key is range 0 .. 2047;

   -- Array type
   type Hex_Map_Array is array (Hex_Key) of Unbounded_String;

   -- The array itself, visible to other units
    Manufacturer_Lookup : constant Hex_Map_Array := (
      16#01# => To_Unbounded_String("AMD"),
      16#02# => To_Unbounded_String("AMI"),
      16#03# => To_Unbounded_String("Fairchild"),
      16#04# => To_Unbounded_String("RAMXEED Limited"),
      16#05# => To_Unbounded_String("GTE"),
      16#06# => To_Unbounded_String("Harris"),
      16#07# => To_Unbounded_String("Hitachi"),
      16#08# => To_Unbounded_String("Inmos"),
      16#09# => To_Unbounded_String("Intel"),
      16#0a# => To_Unbounded_String("I.T.T."),
      16#0b# => To_Unbounded_String("Intersil"),
      16#0c# => To_Unbounded_String("Monolithic Memories"),
      16#0d# => To_Unbounded_String("Mostek"),
      16#0e# => To_Unbounded_String("Freescale (Motorola)"),
      16#0f# => To_Unbounded_String("National"),
      16#10# => To_Unbounded_String("NEC"),
      16#11# => To_Unbounded_String("RCA"),
      16#12# => To_Unbounded_String("Raytheon"),
      16#13# => To_Unbounded_String("Synaptics"),
      16#14# => To_Unbounded_String("Seeq"),
      16#15# => To_Unbounded_String("NXP (Philips)"),
      16#16# => To_Unbounded_String("Synertek"),
      16#17# => To_Unbounded_String("Texas Instruments"),
      16#18# => To_Unbounded_String("Kioxia Corporation"),
      16#19# => To_Unbounded_String("Xicor"),
      16#1a# => To_Unbounded_String("Zilog"),
      16#1b# => To_Unbounded_String("Eurotechnique"),
      16#1c# => To_Unbounded_String("Mitsubishi"),
      16#1d# => To_Unbounded_String("Lucent (AT&T)"),
      16#1e# => To_Unbounded_String("Exel"),
      16#1f# => To_Unbounded_String("Atmel"),
      16#20# => To_Unbounded_String("STMicroelectronics"),
      16#21# => To_Unbounded_String("Lattice Semi."),
      16#22# => To_Unbounded_String("NCR"),
      16#23# => To_Unbounded_String("Wafer Scale Integration"),
      16#24# => To_Unbounded_String("IBM"),
      16#25# => To_Unbounded_String("Tristar"),
      16#26# => To_Unbounded_String("Visic"),
      16#27# => To_Unbounded_String("Intl. CMOS Technology"),
      16#28# => To_Unbounded_String("SSSI"),
      16#29# => To_Unbounded_String("Microchip Technology"),
      16#2a# => To_Unbounded_String("Ricoh Ltd"),
      16#2b# => To_Unbounded_String("VLSI"),
      16#2c# => To_Unbounded_String("Micron Technology"),
      16#2d# => To_Unbounded_String("SK Hynix"),
      16#2e# => To_Unbounded_String("OKI Semiconductor"),
      16#2f# => To_Unbounded_String("ACTEL"),
      16#30# => To_Unbounded_String("Sharp"),
      16#31# => To_Unbounded_String("Catalyst"),
      16#32# => To_Unbounded_String("Panasonic"),
      16#33# => To_Unbounded_String("IDT"),
      16#34# => To_Unbounded_String("Cypress"),
      16#35# => To_Unbounded_String("DEC"),
      16#36# => To_Unbounded_String("LSI Logic"),
      16#37# => To_Unbounded_String("Zarlink (Plessey)"),
      16#38# => To_Unbounded_String("UTMC"),
      16#39# => To_Unbounded_String("Thinking Machine"),
      16#3a# => To_Unbounded_String("Thomson CSF"),
      16#3b# => To_Unbounded_String("Integrated CMOS (Vertex)"),
      16#3c# => To_Unbounded_String("Honeywell"),
      16#3d# => To_Unbounded_String("Tektronix"),
      16#3e# => To_Unbounded_String("Oracle Corporation"),
      16#3f# => To_Unbounded_String("Silicon Storage Technology"),
      16#40# => To_Unbounded_String("ProMos/Mosel Vitelic"),
      16#41# => To_Unbounded_String("Infineon (Siemens)"),
      16#42# => To_Unbounded_String("Macronix"),
      16#43# => To_Unbounded_String("Xerox"),
      16#44# => To_Unbounded_String("Plus Logic"),
      16#45# => To_Unbounded_String("SanDisk Technologies Inc"),
      16#46# => To_Unbounded_String("Elan Circuit Tech."),
      16#47# => To_Unbounded_String("European Silicon Str."),
      16#48# => To_Unbounded_String("Apple Computer"),
      16#49# => To_Unbounded_String("Xilinx"),
      16#4a# => To_Unbounded_String("Compaq"),
      16#4b# => To_Unbounded_String("Protocol Engines"),
      16#4c# => To_Unbounded_String("SCI"),
      16#4d# => To_Unbounded_String("ABLIC"),
      16#4e# => To_Unbounded_String("Samsung"),
      16#4f# => To_Unbounded_String("I3 Design System"),
      16#50# => To_Unbounded_String("Klic"),
      16#51# => To_Unbounded_String("Crosspoint Solutions"),
      16#52# => To_Unbounded_String("Alliance Memory Inc"),
      16#53# => To_Unbounded_String("Tandem"),
      16#54# => To_Unbounded_String("Hewlett-Packard"),
      16#55# => To_Unbounded_String("Integrated Silicon Solutions"),
      16#56# => To_Unbounded_String("Brooktree"),
      16#57# => To_Unbounded_String("New Media"),
      16#58# => To_Unbounded_String("MHS Electronic"),
      16#59# => To_Unbounded_String("Performance Semi."),
      16#5a# => To_Unbounded_String("Winbond Electronic"),
      16#5b# => To_Unbounded_String("Kawasaki Steel"),
      16#5c# => To_Unbounded_String("Bright Micro"),
      16#5d# => To_Unbounded_String("TECMAR"),
      16#5e# => To_Unbounded_String("Exar"),
      16#5f# => To_Unbounded_String("PCMCIA"),
      16#60# => To_Unbounded_String("LG Semi (Goldstar)"),
      16#61# => To_Unbounded_String("Northern Telecom"),
      16#62# => To_Unbounded_String("Sanyo"),
      16#63# => To_Unbounded_String("Array Microsystems"),
      16#64# => To_Unbounded_String("Crystal Semiconductor"),
      16#65# => To_Unbounded_String("Analog Devices"),
      16#66# => To_Unbounded_String("PMC-Sierra"),
      16#67# => To_Unbounded_String("Asparix"),
      16#68# => To_Unbounded_String("Convex Computer"),
      16#69# => To_Unbounded_String("Quality Semiconductor"),
      16#6a# => To_Unbounded_String("Nimbus Technology"),
      16#6b# => To_Unbounded_String("Transwitch"),
      16#6c# => To_Unbounded_String("Micronas (ITT Intermetall)"),
      16#6d# => To_Unbounded_String("Cannon"),
      16#6e# => To_Unbounded_String("Altera"),
      16#6f# => To_Unbounded_String("NEXCOM"),
      16#70# => To_Unbounded_String("Qualcomm"),
      16#71# => To_Unbounded_String("Sony"),
      16#72# => To_Unbounded_String("Cray Research"),
      16#73# => To_Unbounded_String("AMS(Austria Micro)"),
      16#74# => To_Unbounded_String("Vitesse"),
      16#75# => To_Unbounded_String("Aster Electronics"),
      16#76# => To_Unbounded_String("Bay Networks (Synoptic)"),
      16#77# => To_Unbounded_String("Zentrum/ZMD"),
      16#78# => To_Unbounded_String("TRW"),
      16#79# => To_Unbounded_String("Thesys"),
      16#7a# => To_Unbounded_String("Solbourne Computer"),
      16#7b# => To_Unbounded_String("Allied-Signal"),
      16#7c# => To_Unbounded_String("Dialog Semiconductor"),
      16#7d# => To_Unbounded_String("Media Vision"),
      16#7e# => To_Unbounded_String("Numonyx Corporation"),
      others => To_Unbounded_String("?")
   );

end Manufacturer_Codes;
